version: 0.0
os: linux
files:
   - source: /
     destination: /var/smart-recipes/
permissions:
   - object: /var/smart-recipes
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location : ./server-init.sh  
      runas: root
